# Generated by Django 5.0.1 on 2024-01-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_team_facebook_team_linkedin_team_twitter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='team',
            name='youtube',
        ),
    ]
