# Generated by Django 5.0.1 on 2024-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_remove_team_facebook_remove_team_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com'),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com'),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(default='https://www.twitter.com'),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube',
            field=models.URLField(default='https://www.youtube.com'),
        ),
    ]
