# Generated by Django 5.0.1 on 2024-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='lien',
            field=models.URLField(default='http://example.com'),
        ),
    ]
