# Generated by Django 5.0.1 on 2024-01-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_team_facebook_team_linkedin_team_twitter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
